"""api models v0.1.1

Revision ID: 30bd4dd75bd4
Revises: 
Create Date: 2017-02-07 23:22:59.328000

"""

# revision identifiers, used by Alembic.
revision = '30bd4dd75bd4'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('charge', sa.Numeric(), nullable=False),
    sa.Column('site', sa.Enum('Consult', name='sites'), nullable=True),
    sa.Column('is_frontend', sa.Boolean(), nullable=True),
    sa.Column('is_developer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_api'))
    )
    op.create_index(op.f('ix_api_client_id'), 'api', ['client_id'], unique=False)
    op.create_table('account',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('api_pk', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('joined', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('HR', 'Mentor', 'Talent', name='roles'), nullable=False),
    sa.ForeignKeyConstraint(['api_pk'], ['api.pk'], name=op.f('fk_account_api_pk_api')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_account')),
    sa.UniqueConstraint('email', 'api_pk', name=op.f('uq_account_email'))
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=False)
    op.create_table('api_log',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('account_pk', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('start_ts', sa.DateTime(), nullable=False),
    sa.Column('runtime', sa.Float(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('msg', sa.String(), nullable=False),
    sa.Column('error_code', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_pk'], ['account.pk'], name=op.f('fk_api_log_account_pk_account')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_api_log'))
    )
    op.create_table('verification',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('account_pk', sa.Integer(), nullable=True),
    sa.Column('vhash', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_pk'], ['account.pk'], name=op.f('fk_verification_account_pk_account')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_verification')),
    sa.UniqueConstraint('vhash', name=op.f('uq_verification_vhash'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification')
    op.drop_table('api_log')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_api_client_id'), table_name='api')
    op.drop_table('api')
    ### end Alembic commands ###
