"""api models v0.1.1

Revision ID: fd60126de32c
Revises: 
Create Date: 2017-02-06 22:55:06.085000

"""

# revision identifiers, used by Alembic.
revision = 'fd60126de32c'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('joined', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text(u'true'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('role', sa.Enum('HR', 'Mentor', 'Talent', name='roles'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    ### end Alembic commands ###
